server:
  port: 8081   # Gateway port

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: graph-service
          uri: http://localhost:8080   # your graph-service
          predicates:
            - Path=/api/graph/**, /api/professors/**, /api/paper/**

        - id: scraper-service
          uri: http://localhost:8082  #scraper-service
          predicates:
            - Path=/api/fetch-author/**, /api/fetch-works-by-author/**, /api/fetch-work/**
          # filters:
          #   - StripPrefix=1
