spring:
  data:
    neo4j:
      uri: neo4j+s://f06161fc.databases.neo4j.io
      username: neo4j
      password: 12345678
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
# logging:
#   level:
#     org:
#       hibernate:
#         type:
#           descriptor:
#             sql: trace
#         stat: debug

server:
  port: 8080