server:
  port: 8081

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: graph-service
          uri: http://graph:8082
          predicates:
            - Path=/api/graph/**, /api/professors/**, /api/paper/**
          

        - id: scrappy-service
          uri: http://scrappy:8083
          predicates:
            - Path=/api/fetch-author/**, /api/fetch-works-by-author/**, /api/fetch-work/**
          filters:
            - StripPrefix=1

        
